### ISSUE TITLE
Call Bombing not working!!!

### ISSUE THREAD

**Issue by BonnY0** [TheSpeedX/TBomb#200] opened 2020-10-27 17:46 UTC
Call Bombing is not working for Bosnia +387 pls fix

**Comment by 0n1cOn3** [comment] 2020-10-28 01:53
Call Bombing is only for India.

**Comment by wildwolf01-star** [comment] 2020-10-28 09:21
> Call Bombing is only for India.

But its not working in india (+91)

**Comment by chankruze** [comment] 2020-10-28 14:24
> > Call Bombing is only for India.
> 
> But its not working in india (+91)

Run the script, enter your number and record your phone, share that recording.

**Comment by TheSpeedX** [comment] 2020-10-28 19:40
Duplicate of #198

**Closed by TheSpeedX** 2020-10-28 19:40 UTC
